on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt
        pip install pyinstaller

    # Step 4: Debug directory structure to confirm app.py exists
    - name: Debug repository structure
      run: |
        echo "Current Working Directory:"
        pwd
        echo "Repository Structure:"
        ls -R .

    # Step 5: Build the executable
    - name: Build LeadgerDesktop executable
      run: |
        pyinstaller --onefile --name=LeadgerDesktop.1.$(date +'%Y%m%d%H%M%S') --noconsole \
        --add-data "templates:templates" \
        --add-data "instance:instance" \
        --icon=LeadgerApp/icon.ico app.py
        cp -r instance dist/instance
        mv dist LeadgerDesktop_$(date +'%Y%m%d%H%M%S') # Rename dist to package_timestamp
        # Save the executable name for future reference
        echo "EXECUTABLE_NAME=LeadgerDesktop_$(date +'%Y%m%d%H%M%S)/LeadgerDesktop.1.$(date +'%Y%m%d%H%M%S').exe" >> $GITHUB_ENV

    # Step 6: Zip the LeaderDesktop folder
    - name: Zip the LeaderDesktop folder
      run: |
        cd LeadgerDesktop_$(date +'%Y%m%d%H%M%S')
        zip -r ../LeaderDesktop_$(date +'%Y%m%d%H%M%S').zip .

    # Step 7: Create a GitHub release and upload the .zip file
    - name: Create GitHub Release and upload the zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get the current date for the release tag
        RELEASE_TAG=$(date +'%Y%m%d%H%M%S')

        # Create a GitHub release using the GitHub API
        RELEASE_RESPONSE=$(curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -d "{\"tag_name\": \"$RELEASE_TAG\", \"name\": \"Release $RELEASE_TAG\", \"body\": \"Release of LeadgerDesktop executable.\"}" \
        https://api.github.com/repos/prasad3936/LedgerDesktop/releases)

        # Extract the release ID from the response
        RELEASE_ID=$(echo $RELEASE_RESPONSE | jq -r .id)

        # Upload the zip file as an asset to the release
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -H "Content-Type: application/zip" \
        --data-binary @LeaderDesktop_${RELEASE_TAG}.zip \
        https://uploads.github.com/repos/prasad3936/LedgerDesktop/releases/$RELEASE_ID/assets?name=LeaderDesktop_${RELEASE_TAG}.zip
