name: Create Release and Upload Executable

on:
  workflow_run:
    workflows: ["Build Executable"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Download the artifact from the first workflow
    - name: Download executable artifact
      uses: actions/download-artifact@v3
      with:
        name: LeadgerDesktop-executable

    # Step 2: Create a GitHub release
    - name: Create GitHub Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get the current date for the release tag
        RELEASE_TAG=$(date +'%Y%m%d%H%M%S')

        # Create a GitHub release using the GitHub API
        RELEASE_RESPONSE=$(curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -d "{\"tag_name\": \"$RELEASE_TAG\", \"name\": \"Release $RELEASE_TAG\", \"body\": \"Release of LeadgerDesktop executable.\"}" \
        https://api.github.com/repos/prasad3936/LedgerDesktop/releases)

        # Extract the release ID from the response
        RELEASE_ID=$(echo $RELEASE_RESPONSE | jq -r .id)

    # Step 3: Upload the `.exe` to the release
    - name: Upload executable to the release
      run: |
        # Get the path of the downloaded executable
        EXE_PATH="./LeadgerDesktop_$(date +'%Y%m%d%H%M%S')/LeadgerDesktop.1.$(date +'%Y%m%d%H%M%S').exe"

        # Upload the .exe as an asset
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/octet-stream" \
        --data-binary @$EXE_PATH \
        https://uploads.github.com/repos/prasad3936/LedgerDesktop/releases/${{ steps.create_release.outputs.id }}/assets?name=LeadgerDesktop.exe
